apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "ipu-waha-korero"
  region: "us-east-1"
  
nodeGroups:
  - name: ng-1
    instanceType: c5.large
    desiredCapacity: 2

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "api", "controllerManager", "scheduler"]
